### ISSUE TITLE
与阿里的ARouter区别在哪里呢？

### ISSUE THREAD

**Issue by shenxiaolin** [BaronZ88/Router#1]
https://github.com/alibaba/ARouter

**Comment by jamesliao333** [comment]
最大的不同就是一个是安居客的，一个是阿里的。。。 
这个相对简单，只支持Activity的跳转.. 
阿里的ARouter 还支持Fragement... 
还有AOP思路的拦截器IInterceptor 和 服务IProvider ... 功能强大好多好多...

**Comment by ByronNote** [comment]
是的，最大的不同就是 Router 还很简陋，远远没有 ARouter 强大。之所以选择自己开发一方面是因为 ARouter 的很多功能是我们现在所不需要的，现阶段我们需要一个更加简洁路由库；二是自己开发的能更加契合我们的业务；再有一点，偶尔重复造轮子也是有必要的。当然 Router 的功能还会不断完善。
